version: '3.9'
services:
  server:
    image: custom-openjdk
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo-db:localhost

  
  mongo-db:
    image: mongo 
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME: "root"
    #   - MONGO_INITDB_ROOT_PASSWORD: "example"