version: '3.9'
services:
  server:
    image: custom-openjdk
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: ankushmongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:aditya
      - MONGO_INITDB_ROOT_PASSWORD:aditya23
